# Set theme
remote_theme: daviddarnes/garth

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-paginate
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'My blog'
description: 'This is my new blog'
permalink: pretty
logo: "https://1.gravatar.com/userimage/244506044/ff8de803bc671bcfe381da14e0e7abfe?size=256"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "Have you ever wondered why Rosetta's stone is of such importance to deciphering hieroglyphs? A single piece of stone with engravings in an unknown (Ancient Egyptian) and in a widely attested language (Ancient Greek) once paved the way to understand an ancient culture which had been lost for many centuries. I think there exists also an analogy between this history and transmission and developement of knowledge. When a culture becomes  e"
