# Set theme
remote_theme: daviddarnes/garth

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Set plugins
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'steviefurxhiu'
description: 'This is my new blog'
permalink: pretty
logo: "https://1.gravatar.com/userimage/244506044/997afad51b95ec3be644523e58d311ed?size=256"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: 'New post every two weeks.'
