# Set theme
remote_theme: daviddarnes/garth

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-paginate
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'My blog'
description: 'This is my new blog'
permalink: pretty
logo: "https://0.gravatar.com/userimage/244506044/5843d01eb91168ac9346fa5604038d27?size=256"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "There isn't much going on here yet, but watch this space"
